---
title: "belief_systems_extra"
author: "Kevin Kiley"
date: "2/24/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```







# Measures of Attitude Structures


There are many dimesnions along which this kind of belief systems can vary, but I consider two here that are relevant for thinking about constraint over time. First, they can vary in which beliefs they seek to constrain, what I call the belief system's extensiveness. For example, a strong religious belief system might attempt to constrain beliefs across a number of seemingly different domains. This would include not just beliefs about the spiritual and sacred, but also beliefs about family structures, morality, food consumption, and more. In fact the strongest religious belief systems seem to structure people's entire cognition. A weak religious belief system might focus on constraining people's beliefs about the spiritual and sacred but make no claims on other domains.

Second, belief systems can vary in the degree to which they constrain beliefs, what I call intensiveness. In providing considerations, a belief sy... A belief system could, in theory, provide considerations on both sides of an issue, leading people to struggle to maintain consistency. American culture tends to do this on a number of issues, such as marriage [].

An important extension is to recognize that belief systems should not only be thought of as simply constraining. Because belief systems are competing in an ecology of beliefs, a belief system might destablize some beliefs if it provides a set of considerations orthogonal to other cultural influences. For example, if American society generally supports divorce between unhappy couples, but a religious tradition strongly discourages divorce, perhaps by making it a religious taboo, people in that tradition will consume *more* conflicting considerations than a person outside it. This might lead them to be less stable on that issue than other people who do not participate in that religious tradition. 




# Attitude Constraint

The concept of constraint is often invoked to describe a patterning or clustering of attitudes or behaviors in the population. Under this definition, which Converse calls static constraint, constraint is simply "the success we would have in predicting, given initial knowledge that an individual holds a specified attitude, that he holds certain further ideas and attitudes" [@converse: p. ]. This kind of population-level constraint can arise for a number of reasons, only one of which is any sort of cognative linkage. For example, this form of constraint can emerge if people who are socialized to hold one attitude (opposition to abortion) are also socialized to hold another (support for gun ownership), or it could emerge through the joint processes of homophily and social influence [@dellaposta2017]. This form of constraint does not require people to have any comprehension that attitudes are related.

However, it is Converse's second definition of constraint that is frequently implied in sociological studies of attitude structuring, especially in the sociology of culture. This form, which Converse calls dynamic constraint, is assumed to reside in people's heads. Under this definition, "a change in the perceived status (truth, desirability, and so forth) of one idea-element would *psychologically* require, from the point of view of the actor, some compensating change(s) in the status of idea-elements elsewhere in the configuration" [@converse: p. , emphasis in original]. This is the definition that is implicitly invoked when researchers suggest that the co-occurence of attitudes in the population reflects the cultural schema that govern cognition [@dimaggio; @goldberg; @baldassarri].

It is this second form of constraint that researchers of cultural sociology most often seek to demonstrate and is the focus of this paper. To be clear, it is not necessary for people to be able to explicitly articulate that two ideas are linked for them to be linked in thier minds. Schematic processing that is assumed to produce constraint can often occur below the domain of discusrive processing [@lizardo]. What defines this form of constraint is that people feel (consciously or unconsciously) like they cannot change one view without changing the other or that holding two beliefs are incompatible and that they must change one to align with the other -- even if it is just because they feel like their combination of positions is lonely [@martin]. 

## Measures of Constraint

The most common approach to measuring this cognitive form of constraint in the social sciences is examining the pairwise relationships between survey items in cross-sectional data, typically using covariance or correlation [@baldassarri2008; @boutyline2017a; @converse1964; @dellaposta2015]. Related measures designed to address measurement error in individual responses [@ansolabehere2008] still tend to look at the pairwise relationship between latent beliefs. 

These correlational models rest on what I call the "diametric assumption" that beliefs are constrained when they covary across people, that people who are high on the first attitude are high on the second, while people who are low on the first attitude are low on the second. While this is good evidence for the static variation of constraint -- that two issues tend to cluster in the population -- it is not necessarily indicative of a cognitive connection in people's heads. Under this logic, if liberals and conservatives have opposite positions, then they are assumed to understand a link between them, even if they, in their own heads, do not. Similarly, if they do not have opposite positions, neither is assumed to be constrained in their thinking, even if members of both groups subjectively understand their belief system to imply that position (the theoretical definition of the cognitive version of constraint). But there are often times when similar belief systems constrain people to the same position in belief space. For example, all varities of American popular nationalism uncovered by Bonikowski and DiMaggio [-@bonikowski2016] restrict people to some level of agreement that it is important for Americans to have American citizenship and some level of pride in the Armed Forces. No form of popular nationalism rejects these, saying that Americans should not have U.S. citizenship, but that does not make these unconstrained forms of thought.

This logical fallacy, assuming that Belief 1 is associated with Belief 2 only if Belief 1's opposite  is associated with Belief 2's opposite, is also called "denying the antecedent" or the "fallacy of the inverse," and should be familiar to social scientists. Avoiding this problem is the reason classical statistical tests in the social sciences have the structure they do: rejecting a null hypothesis rather than affirming an alternative hypothesis, since there are always other things that could have caused an outcome. The statement $P \to Q$ (if conservative, then oppose abortion) only implies one conclusion (the contrapositive), $\lnot Q \to \lnot P$ (if not oppose abortion, not conservative). It does not imply the the inverse $\lnot P \to \lnot Q$ (not conservative, not oppose abortion). Just because P implies Q does not mean it is the only path to Q. 

The problem is evident if we consider religious belief systems. Protestant theology (which most people would agree is a constrained belief system with a set of logical implications) confines adherents to a belief space of monotheism, belief in angels and demons, and rejection of the pope's infallibility. In protestants' minds, these beliefs are linked -- they cannot hold one without holding another -- and if a person abandoned protestantism, they would likely drop beliefs about monotheism, angels, and demons. But just because rejecting the pope's infallibility is linked to monotheism for protestants does not mean these beliefs are linked for everybody in the population. Nobody would say rejection of monotheism or demons would require acceptance of the pope's infallibility.

This means that while correlational methods are good for describing certain patterns of attitude clustering in the population, they are not necessarily good for getting into people's heads. 

A more recent development in schema measurement are relational and correlational class analysis methods, which attempt to partition people into groups that have similar patterns of relationships among beliefs, allowing for heterogeneous and non-oppositional belief systems in the same population [@goldberg2011; @boutyline2017]. However, the diametric assumption still underlies interpretation of these methods. If people are located in opposite positions, researchers employing these methods assume that people see the same "logic" of a space, which might not be warranted. For example, Baladassarri and Goldberg assume that "a high-earning and secular Manhattan lawyer, squeezed by her progressive leanings on moral issues and her support for fiscal austerity" and "a working-class devout churchgoer torn between his moral conservatism and redistributive economic interests" see politics through the same logic, though this might not be true [@baldassarri: p. 46]. In fact it is hard to imagine that these people see political conflict as an opposition between "libertarian" thought on one hand and "populist" thought on the other, when the main political parties align orthogonal to this axis. What is more plausible is that these peoples views are simply unconstrained by the dominant paradigm, not a separate belief structure.

An exception to this reliance on the diametric assumption is Martin's entropic measures of belief systems [@martin2002; @martin1999]. Martin's approach allows for a variation of constraint he calls "consensus," a form of constraint in which all people in a group hold the same set of beliefs. However, like other researchers, Martin assumes that only diametric positioning -- what he calls "tightness" -- is evidence of a cognitive link between ideas. But his focus on small communities highlights problems with this assumption. We could imagine a community that cognitively links veganism and yoga and also makes belief in these two things an important component of group membership, so there are no people in the group who reject both (which would be required for finding "tightness" in this group). For Martin, this pattern would not indicate a cognitive connection even when members presumably believe there to be one.

These approaches have produced insights into the structuring of the population's beliefs in different domains and about the sources of different forms of constraint, but they all overlook a central component of Converse's formulation: movement. These authors repeatedly invoke the imagery of movement to explain what constraint is (emphasis added in all):

- "However, these beliefs are still tightly connected, in that *movement* in one implies *movement* in the other" [@martin2002: p. 868]. "Tightness, as defined above, can be interpreted as the imposition of *rules of movement* within the belief space (think of the difference between the constrained motion of driving on surface streets and the unconstrained motion of four-wheeling on the beach). Consensus, on the other hand, can be interpreted as a gross *inability to move away from* some privileged areas of the belief space toward others (without channeling in particular directions whatever degree of *motion* is allowed)" [@martin2002: p. 874]. 

- "we might best see the distribution of people in this space as giving us clues about the *rules of motion* in the belief space. If one were to take a picture of some well populated area from a low-orbiting satellite, and marked a spot wherever there was a car, one would be able to figure out rather well where the roads were, and where cars were allowed to go. It is these analogous *rules of movement* that will give us clues as to the nature of social cognition" [@martin2000a: p. 11].

- "Culture, in this context, can be understood as the unspoken set of rules that tie beliefs together by restricting *movement* in this space along certain axes, which demarcate different social worlds" [@goldberg2011: p. 1403].

- "We therefore interpret different *axes of movement in a belief space* ... as the empirical signature of ideological constraint" [@baldassarri2014: 59].

- "attitudes toward science and religion *move* in tandem" [@dimaggio2018a: p. 40].

These researchers understand constraint to be a dynamic phenomenon, but in these studies dynamics are inferred from a snapshot and, importantly, not tested over time. Because people are arrayed along a diagonal in belief space, they are assumed to only travel along this diagonal [@martin2002; @baldassarri2014]. Because people are clustered in portions of the belief space, they are assumed not to move from one cluster to another. These are not unreasonable assumptions, but they are assumptions.

## The Problem of Movement

Given the above discussion, a seemingly obvious approach to evaluating the cognitive form of constraint would be to look at people who make more-or-less simultaneous changes in attitudes over time as a window into the structuring of beliefs in the general public. If a person changes his mind about the morality of homosexual activity and simultaneously (or subsequently in short order) changes his mind about whether homosexual people should be allowed to get married, we can be more confident that a person understands those ideas as related. But this approach faces limitations.

First, changing from one belief system to another might not require simultaneous changes in belief. Consider the Catholic who converts to protestantism, abandoning a belief in the pope's infallability but maintaining belief in god.[^strongversion] In both settings he is in a constrained belief system, but only one belief changed. There are presumably other beliefs that changed along with this view of the pope's infallability, but they might not be asked in a survey.

[^strongversion]: There is, presumably, a strong version of this change in which people go from believing in the Catholic "God" and not believing in the Protestant "God" to the reverse, thereby conforming to the "diametric" belief system. Such a change would be hard to capture in survey data.

The second reason is that when attitudes are observed over time, people appear to change quite frequently and in non-durable ways [@alwin; @houthastings]. While this change is often interpreted as "measurement error," a theoretically grounded interpretation is that these transient changes reflects a degree of ambivalence among the population [@zaller2012]. In this framework, people internalize diverse considerations in favor of and against an issue and, on the basis of short-term temporary influence, connstruct new opinions at the time of each interview. The fact that across several domains stability is associated with the attention people pay to the topic suggests that variation is not random measurement error, but patterned attitude structuring [@freeder2019]. 

In some respects, this degree of ambivalence suggests that attitudes are, in general, not constrained. Large swaths of the population are perfectly capable of expressing different attitudes over time with no subsequent alteration of other other attitudes. However, inferring the behavior of non-changers from the behavior of changers is problematic. If the people who change are fundamentally different that people who do not change, our inferences about pairwise change might be flawed. And there are significant reasons to believe that changers' cognition is fundamentally different than non-changers in ways that matter for measuring constraint.

## Opinion Behavior and Belief Systems


## Measuring Belief Systems

Identifying ...  ...  people constrained to give the same range of responses over time. 












## Data and Measures

### The NSYR

To test the above propositions about dynamic constraint, I look at the structuring of belief systems by religious organizations for young adults transitioning to adulthood. Data comes from the National Study of Youth and Religion, a panel study that surveyed adolescents four times over a 10-year window. In the survey's first wave, respondents were between 13 and 17. The NSYR has been previously used to show the effect of beliefs on behavior. 

In waves 2 through four, respondents were asked a set of questions about religious, moral, and family structure beliefs. Table XXX presents these questions.[^vaisey]

[^vaisey]: Ideally, this analysis would include the "how decide" question that Vaisey explores in his work [@vaisey2009; @vaisey2010], a measure that presumably reflects where people ultimately locate the locus of moral authority -- within themselves out outside themselves. Unfortunately, because of coding problems, that measure is only available for less than 7 percent of respondents at wave 3.

Nine of these questions pertain to religious beliefs, such as the belief in heaven and an afterlife, belief in angels and demons, and belief in god. Three of these questions deal with morality or the relationship between religious beliefs and behavior. And the final six deal with morality around sex, gender roles, and family structures. 

These ... and it is important to have quesitons that cross domains. Importantly, we know that religious organizations seek to bring these distinct under the same belief sturcture framework, the exact kind of linkages that belief systems theories posit. We can also ... The belief structure of an evangelical church might tie christian theology to moral absolutism and strict codes around family structures. A unitarian church ... 

Some belief structures should be more elaborated than others. For example, we can imagine a religious group that does not seek to constrain the views on family formation that its members have. Members of these congregations might have diverse views on family sturctures and gender roles, but similar. ... 

### Measures

*Belief Systems:* I use a graph-based approach to measure the presence of structured belief systems. I first calculate the total absolute pairwise distance between people on these 19 beliefs, with all questions scaled between 0 and 1. I then use these distances to construct a network of people, weighted by the distance between these beliefs.

Unlike relational or correlational class methods, I do not consider people demonstrating opposite belief structures to be displaying similar logics, but rather different belief structures. 

I  measure the constraint of a person's belief system by measuring his or her distance from the center of his belief system. People close to the center of the belief system have ... 


Belief Change: 

*Socializations:* The first hypothesis calls for a measure of participation in an ideological sturcturing organization. I use religious denomination at wave 1 and frequency of church attendance at wave 1 as independent measures. 

*Social Structure Changes:* Social structures are both a predictor and an outcome of different hypotheses presented above. I focus on two kinds of social structure. The first is the fequency of religious participation and the institution in which a person participates, as measured by religious denomination. Second, I evaluate changes in social networks, in particular the share of close friends who have similar beliefs as the respondent. 





### Hypothesis Tests

To test whether institutional participation ... , I  ... ... 

To ... fixed-effects model to test whether . A fixed-effects approach controls for time-invariant factors. 


# Results

## Religious and Moral Belief Systems

... with many people demonstrating ... ideosyncratic views. ...  


Partitioning algorithm finds four main clusters, with many people demonstrating ideosyncratic beliefs. This is not problematic and is expected. ... Our expectation is that these people are 

The first two belief systems corresponds to traditional ... It reflects a belief in ... The distinction between the two groups revolves around morality. The first group, moral absolutists, believe that morality is not relative and that we should not change morality with the times. People in the second belief system tend to hold traditional Christian beliefs, but reject the notion that such beliefs require them to be moral absolutists. A third, small belief system, reflects people who are not ... They reject belief in ... and god, and are moral relativists. 



Presents a distribution of how "constrained" each person's belief system is -- how close they are to the center of their respective cluster, separated by belief system.  

## Institutional Structuring of Belief Systems

... I predict ... using people's social background at wave 1 of the NSYR. ... The closer a person is to the center of their respective cluster, the less likely they are to change any particular belief between waves 2 and 3. Table ... regresses change between waves 2 and 3 on the closeness a person

It shows that 






### Constraint and Stability

Finally, I use a fixed-effects model to estimate the effect of constraint on stability within people. I calcualte people's responses at waves 2, 3, and 4. If constraint, then people who move toward the center of their respective belief cluster will demonstrate more stability as a result. A person who comes to understand an evangelical worldview will become stable as a result. Similarly, because idea elements are interconnected, a loosening of one dimension of the belief system can beget a loosening of other components of the system. 


# Discussion of Results

In general, there are constrained belief patterns. The social landscape of America seems to facilitate three constrained belief systems ... None of these are clear ... of each other, as the belief systems literature often assume. 


## Discussion

This paper does ot deal with the explanations for why intensiveness and extensiveness emerge. 


# Conclusion

This paper argues that belief systems ... should be thought of as socially patterned combinations of considerations that lead people to have similar probabilities of giving particular responses over time. Under this framework, latent class analysis provides a strong methodological instantiation of the theoretical model of a belief system. 

I tested this theoretical framework on religious, moral, and family beliefs n the National Study of Youth and Religion. First, I showed that within-group variance at a single time point strongly predicts the over-time variance in responses. Second, I showed that the latent-class belief system model better predicted the observed counts of response patterns over time than other theoretically plausible models.




On one hand, this frequent movement suggests that attitudes tend not to be constrained, as people seem free to change one attitude without changing attitudes that researchers expect to be linked. However, work in psychology suggests that the people who understand attitudes as related are the least likely to change [@howe2017], and some members of the population are quite stable in their dispositions over time [@freeder2019; @zaller1992]. This means that people might understand attitudes as related -- the exact definition of this cognitive form of constraint -- and as a result *not* change their attitudes.





