---
title: "Dynamic Constraint: Attitude Stability as a Function of Belief Structuring"
author: "Kevin Kiley"
date: "2/10/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

A key way the social world is assumed to shape individual behavior is by constraining people's understanding of which attitudes, beliefs, and behaviors are compatible [@durkheim]. In is through this process that society is assumed to get "into the heads" of actors and reproduce itself [@something], create patterns of attitude association in the population [@rawlings2020; @dellaposta; @goldberg], and SOEMTHING ELSE.

In sociology, measures of attitude structuring and constraint have tended to focus, in one form or another, on the pairwise relationship between variables in cross-sectional data [@baldassarri2008; @baldassarri2014; @boutyline2017a; @goldberg2011; @hunzaker2019; @martin2002]. This work has led to numerous insights into the structuring of political and cultural thought in different groups, heterogeneity in belief patterns, and the social factors that give rise to constrained thinking.

But the limitation of this approach is apparent in the central metaphor these researchers use to explain constraint: movement. Across these works, constraint is consistently described as limitations on the movement of attitudes over time, but it is rarely measured using within-person, over-time data [for an exception, see @rawlings2020]. In using static measures of constraint, researchers tend to assume that because people hold two ideas at the same time or because beliefs covary in the population, people understand these ideas as related and constraining. But co-occurrence and co-variance in static data does not prove the cognitive linkages or the presence of constraint that these researchers tend to assume [@martin2000a]. The clustering of people in social groups with opposite attitudes could be driven by a number of processes besides cognitive linkage, such as socialization or selection [@vaisey2010; @lewis2018].

Attention to movement is important because, as decades of research have shown, people seem to be highly ambivalent in their opinions over relatively short times frames [@converse1964; @zaller1992]. People frequently vacillate between sides of an issue over two or four years in a way that suggests that they internalize diverse and conflicting considerations on an issue and can be induced by local circumstances to give conflicting responses over time [@swidler2001; @zaller1992]. On one hand, this frequent movement suggests that attitudes are not constrained in the population, as people seem free to change one attitude without changing attitudes that are believed to be linked. However, work in psychology suggests that the people who understand attitudes as related are the least likely to change [@howe2017], and some members of the population are quite stable in their dispositions over time [@freeder2019; @zaller1992]. This means that people might understand attitudes as related -- the exact definition of this cognitive form of constraint -- and as a result *not* change their attitudes.

In this paper, I attempt to reconcile these conceptual and methodological issues by rethinking constraint from a dynamic perspective. Drawing on insights from sociology of culture and cognition, the social psychology of attitude development, and political psychology, I argue that the cognitive form of constraint is not well demonstrated by attitude clustering or even change over time, but rather should be conceptualized as pairwise (or higher-order) stability over time. Attitudes constrain each other when holding one attitude makes a person less likely to change another. 

The goal of this paper is not to claim that constraint is more or less common than other researchers say it is, or even to adjudicate where constraint is or is not present. This paper aims to clarify the theoretical underpinnings of attitude constraint and to bring them in line with contemporary understandings of cultural cognition, attitude development, and attitude stability. By clarifying concepts and providing a methodological framework with which to adjudicate these debates, I hope to suggest a way forward in understanding which beliefs are linked in people's heads and how these linkages emerge.

# Attitude Constraint

The concept of constraint is often invoked to describe a patterning or clustering of attitudes or behaviors in the population. Under this definition, which Converse calls static constraint, constraint is simply "the success we would have in predicting, given initial knowledge that an individual holds a specified attitude, that he holds certain further ideas and attitudes" [@converse: p. ]. This kind of population-level constraint can arise for a number of reasons, only one of which is any sort of cognative linkage. For example, this form of constraint can emerge if people who are socialized to hold one attitude (opposition to abortion) are also socialized to hold another (support for gun ownership), or it could emerge through the joint processes of homophily and social influence [@dellaposta2017]. This form of constraint does not require people to have any comprehension that attitudes are related.

However, it is Converse's second definition of constraint that is frequently implied in sociological studies of attitude structuring, especially in the sociology of culture. This form, which Converse calls dynamic constraint, is assumed to reside in people's heads. Under this definition, "a change in the perceived status (truth, desirability, and so forth) of one idea-element would *psychologically* require, from the point of view of the actor, some compensating change(s) in the status of idea-elements elsewhere in the configuration" [@converse: p. , emphasis in original]. This is the definition that is implicitly invoked when researchers suggest that the co-occurence of attitudes in the population reflect the cultural schema that govern cognition [@dimaggio; @goldberg; @baldassarri].

It is this second form of constraint that researchers of cultural sociology most often seek to demonstrate and is the focus of this paper. To be clear, it is not necessary for people to be able to explicitly articulate that two ideas are linked. Schematic processing that is assumed to produce constraint can often occur below the domain of discusrive processing [@lizardo]. What defines this form of constraint is that people feel (consciously or unconsciously) like they cannot change one view without changing the other or that holding two beliefs are incompatible and that they must change one to align with the other -- even if it is just because they feel like their combination of positions is lonely [@martin]. 

## Measures of Constraint

The most common approach to measuring this cognitive form of constraint in the social sciences is examining the pairwise relationships between survey items in cross-sectional data, typically using covariance or correlation [@baldassarri2008; @boutyline2017a; @converse1964; @dellaposta2015]. Related measures designed to address measurement error in individual responses [@ansolabehere2008] still tend to look at the pairwise relationship between latent beliefs. 

These correlational models rest on what I call the "diametric assumption" that beliefs are constrained when they covary across people, that people who are high on the first attitude are high on the second, while people who are low on the first attitude are low on the second. While this is good evidence for the static variation of constraint -- that two issues tend to cluster in the population -- it is not necessarily indicative of a cognitive connection in people's heads. According to this logic, if liberals and conservatives have opposite positions, then they are assumed to understand a link between them, even if they, in their own heads, do not. If they do not have opposite positions, neither is assumed to be constrained in their thinking, even if members of both groups subjectively understand their belief system to imply that position (the theoretical definition of the cognitive version of constraint). For example, all varities of American popular nationalism uncovered by Bonikowski and DiMaggio [-@bonikowski2016] restrict people to some level of agreement that it is important for Americans to have American citizenship and some level of pride in the Armed Forces. No form of popular nationalism rejects these, saying that Americans should not have U.S. citizenship, but that does not make these unconstrained forms of thought.

This logical fallacy, also called "denying the antecedent" or the "fallacy of the inverse," should be familiar to social scientists. Avoiding this problem is the reason classical statistical tests in the social sciences have the structure they do: rejecting a null hypothesis rather than affirming an alternative hypothesis, since there are always other things that could have caused an outcome. The statement $P \to Q$ (if conservative, then oppose abortion) only implies one conclusion (the contrapositive), $\lnot Q \to \lnot P$ (if not oppose abortion, not conservative). It does not imply the the inverse $\lnot P \to \lnot Q$ (not conservative, not oppose abortion). Just because P implies Q does not mean it is the only path to Q. 

The problem is evident if we consider religious belief systems. Protestant theology (which most people would agree is a constrained belief system with a set of logical implications) confines adherents to a belief space of monotheism, belief in angels and demons, and rejection of the pope's infallibility. In protestants' minds, these beliefs are linked -- they cannot hold one without holding another -- and if a person abandoned protestantism, they would likely drop beliefs about monotheism, angels, and demons. But just because rejecting the pope's infallibility is linked to monotheism for protestants does not mean these beliefs are linked for everybody in the population. Nobody would say rejection of monotheism or demons would require acceptance of the pope's infallibility. There's nobody in the population who is an anti-Protestant on these dimensions -- rejecting belief in a single god, rejecting the existence of angels and demons, but believing in the pope's infallibility.

This means that while correlational methods are good for describing certain patterns of attitude clustering in the population, they are not necessarily good for getting into people's heads. 

A more recent development in schema measurement are relational and correlational class analysis methods, which attempt to partition people into groups that have similar patterns of relationships among beliefs, allowing for heterogeneous and non-oppositional belief systems in the same population [@goldberg2011; @boutyline2017]. However, the diametric assumption still underlies interpretation of these methods. If people are located in opposite positions, researchers employing these methods assume that people see the same "logic" of a space, which might not be warranted. For example, Baladassarri and Goldberg assume that "a high-earning and secular Manhattan lawyer, squeezed by her progressive leanings on moral issues and her support for fiscal austerity" and "a working-class devout churchgoer torn between his moral conservatism and redistributive economic interests" see politics through the same logic, though this might not be true [@baldassarri: p. 46].

An exception to this reliance on the diametric assumption is Martin's entropic measures of belief systems [@martin2002; @martin1999]. Martin's approach allows for a variation of constraint he calls "consensus," a form of constraint in which all people hold the same set of beliefs. However, like other researchers, Martin assumes that only diametric positioning -- what he calls "tightness" -- is evidence of a cognitive link between ideas. But his focus on small communities highlights problems with this assumption. We could imagine a community that cognitively links veganism and yoga and also makes belief in these two things an important component of group membership, so there are no people in the group who reject both (which would be required for finding "tightness" in this group). For Martin, this pattern would not indicate a cognitive connection even when members believe there to be one.

These approaches have produced insights into the structuring of the population's beliefs in different domains and about the sources of different forms of constraint, but they all overlook a central component of Converse's formulation: movement. These authors repeatedly invoke the imagery of movement to explain what constraint is (emphasis added in all):

- "However, these beliefs are still tightly connected, in that *movement* in one implies *movement* in the other" [@martin2002: p. 868]. "Tightness, as defined above, can be interpreted as the imposition of *rules of movement* within the belief space (think of the difference between the constrained motion of driving on surface streets and the unconstrained motion of four-wheeling on the beach). Consensus, on the other hand, can be interpreted as a gross *inability to move away from* some privileged areas of the belief space toward others (without channeling in particular directions whatever degree of *motion* is allowed)" [@martin2002: p. 874]. 

- "we might best see the distribution of people in this space as giving us clues about the *rules of motion* in the belief space. If one were to take a picture of some well populated area from a low-orbiting satellite, and marked a spot wherever there was a car, one would be able to figure out rather well where the roads were, and where cars were allowed to go. It is these analogous *rules of movement* that will give us clues as to the nature of social cognition" [@martin2000a: p. 11].

- "Culture, in this context, can be understood as the unspoken set of rules that tie beliefs together by restricting *movement* in this space along certain axes, which demarcate different social worlds" [@goldberg2011: p. 1403].

- "We therefore interpret different *axes of movement in a belief space* ... as the empirical signature of ideological constraint" [@baldassarri2014: 59].

- "attitudes toward science and religion *move* in tandem" [@dimaggio2018a: p. 40].

These researchers understand constraint to be a dynamic phenomenon, but in these studies dynamics are inferred from a snapshot. Because people are arrayed along a diagonal in belief space, they are assumed to travel along this diagonal [@martin2002; @baldassarri2014]. Because people are clustered in portions of the belief space, they are assumed not to move from one cluster to another. These are not unreasonable assumptions, but they are assumptions.

## The Problem of Movement

Given the above discussion, a seemingly obvious approach to evaluating the cognitive form of constraint would be to look at people who make more-or-less simultaneous changes in attitudes over time as a window into the structuring of beliefs in the general public. If a person changes his mind about the morality of homosexual activity and simultaneously (or subsequently in short order) changes his mind about whether homosexual people should be allowed to get married, we can be more confident that a person understands those ideas as related. But this approach faces limitations.

First, changing from one belief system to another might not require simultaneous changes in belief. Consider the Catholic who becomes a protestant, rejecting the pope's infallability but maintaining belief in god.[^strongversion] Both are constrained belief systems. 

[^strongversion]: There is, presumably, a strong version of this change in which people go from believing in the Catholic "God" and not believing in the Protestant "God" to the reverse, thereby conforming to the "diametric" belief system. Such a change would be hard to capture in survey data, however.

The second reason is that when attitudes are observed over time, people appear to change quite frequently and in non-durable ways [@alwin; @houthastings]. While this change is often interpreted as "measurement error," a theoretically grounded interpretation is that these transient changes reflects a degree of ambivalence among the population [@zaller2012]. In this framework, people internalize diverse considerations in favor of and against an issue and, on the basis of short-term temporary influence, connstruct new opinions at the time of each interview. The fact that in several domains stability is associated with the attention people pay to the topic suggests that variation is not random measurement error, but patterned attitude structuring [@freeder2019]. 

In some respects, this degree of ambivalence suggests that attitudes are, in general, not constrained. Large swaths of the population are perfectly capable of expressing different attitudes over time with no subsequent alteration of other other attitudes. However, inferring the behavior of non-changers from the behavior of changers is problematic. If the people who change are fundamentally different that people who do not change, our inferences about pairwise change might be flawed. And there are significant reasons to believe that changers' cognition is fundamentally different than non-changers in ways that matter for measuring constraint.



## Opinion Behavior

A key finding from decades of work cultural sociology and public opinion is that people consume diverse and contradictory bits of culture, often storing this heterogeneous mixture without taking time to reconcile its contraditions [@martin2010; @swidler2001; @zaller1992]. Without strong motivation to reconcile conflists, people have a hard time keeping conflicting considerations out of their heads [@martin2010; @zaller1992]. As a result, "our heads are full of images, opinions, and information, untagged as to truth value, to which we are inclined to attribute accuracy and plausibility" [@dimaggio1997: p. 267]. In interviews they tend to draw on these diverse considerations, often contradicting themselves, and in repeated surveys people appear to vascillate much more than we would expect if they were stable opinion holders [@zaller1992; @converse1964; @swidler2001]. 

At the same time, an often smaller proportion of the population does clearly articulate the same opinions over time. Features of the social environment, such as the presence of cognitive authorities, facilitates attitude constriant [@martin2002; @rawlings2020]. And work in cultural sociology suggests that attitudes can predict behaviors and patterns of affiliation over time [@vaisey2009; @vaisey2010], which we would not expect if attitudes were temporary constructs shaped by local circumstances.

These two opinion behaviors -- stable beliefs that shape choices and cognition and inconsistent attitudes that matter little for the structuring of beliefs or behaviors -- closely map on to the distinction in psychology between strong attitudes, which "are resistant to change, stable over time, influential on cognition, and influential on action," and weak attitudes, which are not [@howe2017: p. ]. 

A feature of strong attitudes is that they drive people to understand how a particular belief relates to others. At the same time, this patterning of issue relationships is likely to emerge from local interactions, and likely driven by opportunities that are salient in people's local environments. This helps explain why we see strong alignment among partisan dimensions without observing strong population-level constraint -- political debates are highly salient and people can often connect their one or two strong issue positions to what is espoused by political actors [@baldassarri20?]. But they have neither the time nor the energy to connect their issues to all others in the ideological umbrella.

Importantly, attitude strength is not well measured by the intensity with people give a response at a single point in time. Ambivalent people can feel attitudes strongly in one wave and feel the opposite belief strongly in a subsequent wave without any acknowledgement of their incompatibility [@zaller1992]. The empirical signature of strong attitudes is their stability -- people do not change them over time. This is in part because these attitudes become attached to their sense of self, and in part because people have developed strong networks of associations that insulate these attitudes from temporary whims.  

In other words, the people most likely to have constrained cognition are potentially the least likely to change. As Howe and Krosnick note, "Attitudes that can be easily changed are weak and unlikely to shape behavior. The attitudes that most powerfully shape behavior are the hardest to change" [@howe2017: p. 328].

## Hypotheses

The preceding discussion suggests an empirical signature of the cognitive variant of constraint should be a lack of movement in ideas over time. When people view attitudes as linked, holding one of them stable limits the degree to which another can be changed. It does not control how a person moves; it controls when he does not move. The preceeding discussion gives us a set of expectations for how we should expect constrained beliefs to behave.

### Cognitive Authority and Belief Systems

Cognitive authorities are presumed to be the source of attitude structuring [@martin2002; @rawlings2020]. As Converse notes, "the shaping of belief systems of any range into apparently logical wholes that are credible to large numbers of people is an act of creative synthesis characteristic of only a minuscule proportion of any population" [@converse: p. ]. In the religious domain, there is no a priori logic tying together the existence of gods and angels to opposition to evolution and moral absolutism. This is a difficult task that likely requires the assistance of physical objects (Bibles, textbooks), specific instruction (sermons, Sunday school), and likely decades of institutional support. This structuring gives people the cognitive resources to filter out competing considerations and to tie together the elements of the belief system, reinforcing these connections. Similarly, the structuring of ... might require social reinforcement [@rawlings2020].

In general, then, we should expect people who more frequently participate in institutions designed to structure a particular belief system to demonstrate greater structre in their cognition. Exactly how that belief system is structured will depend on the institution the person participates in.

Hypothesis 1: The more time someone spends with belief structuring organizations, the more likely he or she will be to demonstrate a coherent belief system. 

Hypothesis 2: People in similar institutional settings will demonstrate similar belief structures. 

### Belief Systems and Stability

The major proposition from the preceeding discussion is that constrained belief systems will be resistant to change over time.

Hypothesis 3: Constrained belief systems will be correlated with less change over time.

There are two general reasons why we should expect constrained beliefs to demonstrate greater stability. First, people with constrained beliefs will demonstrate less change in their social contexts. Strong belief systems guide people's behavior across domains, including the networks people select into, the institutions in which they choose to participate, and more [@vaiseylizardo]. Heterogeneous belief systems allow people to draw on different considerations when constructing [@harding].

Hypothesis 4: As the constraint of the belief system increases, people demonstrate less change in social structures.

Second, even when they move across social contexts, people with constrained belief systems will be less likely to change their attitudes. Belief systems provide the cognitive tools to reject inconsistent considerations. A person with a constrained belief systems might be less likely to make friends with someone who has a conflicting belief system, but even if they do, that alter will have less influence on them than a person with a less constrained belief system. 

Hypothesis 5: As the structure of a belief system increases, change in social structure will produce less change in beliefs structures.

## Data and Measures

### The NSYR

To test the above propositions about dynamic constraint, I look at the constraint of religious belief systems as young people transition from adolesence to adulthood. Data comes from the National Study of Youth and Religion, a panel study that surveyed adolescents four times over a 10-year window. In the survey's first wave, respondents were between 13 and 17. The NSYR has been previously used to show the effect of beliefs on behavior. 

In waves 2 through four, respondents were asked a set of questions about religious and moral beliefs. Table XXX presents these questions.[^vaisey]

[^vaisey]: Ideally, this analysis would include the "how decide" question that Vaisey explores in his work [@vaisey2009; @vaisey2010]. Unfortunately, because of coding problems, that measure is only available for less than 7 percent of respondents at wave 3.  

### Measures

*Belief Systems:* To measure the presence of structured belief systems. I first calculate the total absolute pairwise distance between people on these 13 beliefs, with all questions scaled between 0 and 1. I then use these distances to construct a network of people, weighted by the distance between these beliefs.

Unlike relational or correlational class methods, I do not consider people demonstrating opposite belief structures to be displaying similar logics, but rather different belief structures. 

I  measure the constraint of a person's belief system by measuring his or her distance from the center of his belief system. People close to the center of the belief system have ... 


Belief Change: 

*Socializations:* The first hypothesis calls for a measure of participation in an ideological sturcturing organization. I use religious denomination at wave 1 and frequency of church attendance at wave 1 as independent measures. 

*Social Structure Changes:* Social structures are both a predictor and an outcome of different hypotheses presented above. I focus on two kinds of social structure. The first is the fequency of religious participation and the institution in which a person participates, as measured by religious denomination. Second, I evaluate changes in social networks, in particular the share of close friends who have similar beliefs as the respondent. 


### Hypothesis Tests

To test whether institutional participation ... , I  ... ... 

To ... fixed-effects model to test whether . A fixed-effects approach controls for time-invariant factors. 


# Results

## Religious and Moral Belief Systems

Looking, three clusters of beliefs emerge. Figure ### ... plots these belief structures. 


The final belief structure, much smaller, rejects belief in the traditional christian elements and embraces a moral relativism. 


The first two belief systems corresponds to traditional ... It reflects a belief in ... The distinction between the two groups revolves around morality. The first group, moral absolutists, believe that morality is not relative and that we should not change morality with the times. People in the second belief system tend to hold traditional Christian beliefs, but reject the notion that such beliefs require them to be moral absolutists. A third, small belief system, reflects people who are not ... They reject belief in ... and god, and are moral relativists. 



Presents a distribution of how "constrained" each person's belief system is -- how close they are to the center of their respective cluster, separated by belief system.  

## Institutional Structuring of Belief Systems

... I predict ... using people's social background at wave 1 of the NSYR. ... The closer a person is to the center of their respective cluster, the less likely they are to change any particular belief between waves 2 and 3. Table ... regresses change between waves 2 and 3 on the closeness a person

It shows that 






### Constraint and Stability

Finally, I use a fixed-effects model to estimate the effect of constraint on stability within people. I calcualte people's responses at waves 2, 3, and 4. If constraint, then people who move toward the center of their respective belief cluster will demonstrate more stability as a result. A person who comes to understand an evangelical worldview will become stable as a result. Similarly, because idea elements are interconnected, a loosening of one dimension of the belief system can beget a loosening of other components of the system. 


# Discussion of Results

In general, there are constrained belief patterns. The social landscape of America seems to facilitate three constrained belief systems ... None of these are clear ... of each other, as the belief systems literature often assume. 






